name: dart_bookstore
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  crypt: ^4.3.1
  dart_jsonwebtoken: ^2.14.2
  dotenv: ^4.2.0
  postgres: ^3.4.8
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  zod_validation: ^1.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
